# Семинар №1
# Введение в линейную алгебру. Векторы. Матрицы и операции с ними. Библиотека NumPy

## Векторы

**Определение** : *Вектором* в n-мерном евклидовом пространстве $\R^{n}$ называется упорядоченый набор чисел $x = (x_1, x_2, ..., x_n)$ - собственно, элемент пространства $\R^{n}$.

Часто вектор удобнее записывать в столбец: 
$$x = \begin{pmatrix}x_1\\x_2\\...\\x_n\\\end{pmatrix}$$

Помимо того, что вектор это набор чисел, вектор еще и геометрический объект, мы его можем отобразить на координатной поскости и в пространстве:

![](imgs/sem1/sem1_1.png) | ![](imgs/sem1/sem1_2.png)

### Операции над векторами

Векторы можно складывать и умножать на скаляр(число). Результатом будет вектор, элементами которого являются результаты поэлементного выполнения операции.

#### Сложение векторов

Геометрически сложение векторов выглядит так:

| для неколлинеарных векторов | для коллинеарных векторов | сложение нескольких векторов |
| --- | --- | --- |
| ![](imgs/sem1/sem1_3.png) | ![](imgs/sem1/sem1_4.png) | ![](imgs/sem1/sem1_5.png) |

**Пример**

![](imgs/sem1/sem1_6.png)

#### Линейные подпространства

- Векторное пространство $\R^{n}$ **замкнуто** относительно операций сложения и умножения на скаляр.

**Определение**: *Линейным (или векторным) подпространством* векторного пространства $L$ называется множество векторов $M$ $\subset$ $L$, замкнутое относительно операций сложения и умножения на скаляр.

**Определение**: *Линейной оболочкой векторов $v_1, v_2, ..., v_n$* называется множество всех линейных комбинаций этих векторов с произвольными коэффициентами: $$M =<v_1, v_2, ..., v_n> = \{\alpha_{1}v_{1} + \alpha_{2}v_{2} + ... + \alpha_{n}v_{n} \ \ | \ \  \alpha_{i}\in \R\}$$

#### ЛНЗ
**Определение**: Векторы $v_1, v_2, ..., v_n$ называются *линейно независимыми*, если никакая линейная комбинация этих векторов не равна нуль-вектору. Иными словами, для любых $\alpha_{i} \in \R$, не все из которых нулевые, выполняется $$\alpha_{1}v_{1} + \alpha_{2}v_{2} + ... + \alpha_{n}v_{n} \ne \overline{0}$$

![](imgs/sem1/sem1_7.png)

#### Базис
**Определение**: Пусть $M$ - линейное подпространство. Базисом в $M$ называется минимальная система векторов $v_1, v_2, ..., v_n$, для которой $M = <v_1, v_2, ..., v_n>$

![](imgs/sem1/sem1_8.png)

Свойства базиса:

- Базис является ЛНЗ
- Векторы из $M$ выражаются через базис единственным способом
- Любую ЛНЗ систему можно дополнить до базиса
- В любой системе образующих можно выбрать базис
- Любые два базиса равномощны. (Это свидетельствует о корректности определения *размерности линейного пространства* как размера базиса в этом линейном пространстве)


**Теорема**: $n+1$ векторов в $n-мерном$ пространстве всегда линейно зависимы.

**Доказательство**: От противного. Пусть Они ЛНЗ => Можно дополнить до базиса => в базисе n+1 векторов и более => противоречие т.к. любые два базиса равномощны. 



Далее поговорим как работать с векторами в `Python` с использованием библиотеки `NumPy`

## Отвлечемся на введение в NumPy

In [1]:
# !conda install numpy
# !pip3 install numpy

In [2]:
import numpy as np

### Одномерные массивы

In [3]:
a = [1, 2, 3]
b = np.array(a, dtype='float64')
print(type(b), type(a))

<class 'numpy.ndarray'> <class 'list'>


***Если типы разные, то идет неявный каст к одному.***

In [4]:
a = [1, 2, 'a']
b = np.array(a)
print("Для list:", type(a[0]),
      "\nДля np.array:", type(b[0]))

Для list: <class 'int'> 
Для np.array: <class 'numpy.str_'>


In [5]:
d = np.array([1, 2, 3])
d

array([1, 2, 3])

In [6]:
type(d)

numpy.ndarray

***Можем посмотреть на все методы класса ``ndarray``.***

In [7]:
set(dir(b)) - set(dir(object))

{'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delitem__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__float__',
 '__floordiv__',
 '__getitem__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__len__',
 '__lshift__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__neg__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',

***Например узнаем размер массива.***

In [8]:
arr = np.array([5, 6, 2, 1, 10], dtype='int32')

In [9]:
arr.nbytes

20

***Если вы не знаете нужной функции, но понимаете, чего хотите, тогда можно воспользоваться поиском в документации.***

In [10]:
np.lookfor('mean value of array') 

Search results for 'mean value of array'
----------------------------------------
numpy.ma.mean
    Returns the average of the array elements along given axis.
numpy.mean
    Compute the arithmetic mean along the specified axis.
numpy.nanmean
    Compute the arithmetic mean along the specified axis, ignoring NaNs.
numpy.put
    Replaces specified elements of an array with given values.
numpy.full
    Return a new array of given shape and type, filled with `fill_value`.
numpy.digitize
    Return the indices of the bins to which each value in input array belongs.
numpy.isrealobj
    Return True if x is a not complex type or an array of complex numbers.
numpy.unpackbits
    Unpacks elements of a uint8 array into a binary-valued output array.
numpy.nanquantile
    Compute the qth quantile of the data along the specified axis,
numpy.ma.dot
    Return the dot product of two arrays.
numpy.count_nonzero
    Counts the number of non-zero values in the array ``a``.
numpy.ma.fix_invalid
    Retur

***Далее можно почитать документацию про контретную функцию.***

In [11]:
?np.ma.mean

Signature:       np.ma.mean(a, *args, **params)
Type:            _frommethod
String form:     <numpy.ma.core._frommethod object at 0x7ff15607e250>
File:            ~/miniconda3/envs/py38/lib/python3.8/site-packages/numpy/ma/core.py
Docstring:      
mean(self, axis=None, dtype=None, out=None, keepdims=<no value>)

Returns the average of the array elements along given axis.

Masked entries are ignored, and result elements which are not
finite will be masked.

Refer to `numpy.mean` for full documentation.

See Also
--------
numpy.ndarray.mean : corresponding function for ndarrays
numpy.mean : Equivalent function
numpy.ma.average : Weighted average.

Examples
--------
>>> a = np.ma.array([1,2,3], mask=[False, False, True])
>>> a
masked_array(data=[1, 2, --],
             mask=[False, False,  True],
       fill_value=999999)
>>> a.mean()
1.5
Class docstring:
Define functions from existing MaskedArray methods.

Parameters
----------
methodname : str
    Name of the method to transform.

In [12]:
np.con*?

np.concatenate
np.conj
np.conjugate
np.convolve

***Посмотрим на количественные характеристики ``ndarray``.***

In [13]:
arr = np.array([[[1, 2, 3, 4],
                [2, 3, 4, 3],
                [1, 1, 1, 1]], 
                [[1, 2, 3, 4],
                [2, 3, 4, 3],
                [1, 1, 1, 1]]])
print(arr)

[[[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]

 [[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]]


In [14]:
print("len:", len(arr), "-- количество элементов по первой оси.",
      "\nsize:", arr.size, "-- всего элементов в матрице.",
      "\nndim:", arr.ndim, "-- размерность матрицы.",
      "\nshape:", arr.shape, "-- количество элементов по каждой оси.")

len: 2 -- количество элементов по первой оси. 
size: 24 -- всего элементов в матрице. 
ndim: 3 -- размерность матрицы. 
shape: (2, 3, 4) -- количество элементов по каждой оси.


***Индексы.***

In [15]:
a = np.array([1, 2, 3, 4])
a[0], a[1]

(1, 2)

***Последний элемент.***

In [16]:
a[-1]

4

***Можем изменять объекты массива.***

In [17]:
a[2] = -1
a

array([ 1,  2, -1,  4])

***``ndarray`` можно использовать в циклах. Но при этом теряется главное преимущество `Numpy` -- быстродействие. Всегда, когда это возможно, лучше использовать операции над массивами как едиными целыми.***

In [18]:
for i in a:
    print(i)

1
2
-1
4


**Задача 1:** Создать numpy-массив, состоящий из первых четырех простых чисел, выведите его тип и размер:

In [19]:
# решение

arr = np.array([2, 3, 5, 7])
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.shape)
print(arr.nbytes)

[2 3 5 7]
int64
<class 'numpy.ndarray'>
(4,)
32


### Создание массивов

In [20]:
a = np.zeros(7, dtype=np.int16) # массив из нулей
b = np.ones(7, dtype=np.float64) # массив из единиц
print(a)
print(b)

[0 0 0 0 0 0 0]
[1. 1. 1. 1. 1. 1. 1.]


***Часто нужно создать нулевой массив такой же как другой.***

In [21]:
c = np.zeros(7, dtype=np.float64)
c

array([0., 0., 0., 0., 0., 0., 0.])

In [22]:
c = np.zeros_like(b, dtype=np.int64)
c

array([0, 0, 0, 0, 0, 0, 0])

***Функция `np.arange` подобна `range`. Аргументы могут быть с плавающей точкой. Следует избегать ситуаций, когда (конец-начало)/шаг -- целое число, потому что в этом случае включение последнего элемента зависит от ошибок округления. Лучше, чтобы конец диапазона был где-то посредине шага.***

In [23]:
a = np.arange(1, 16, 4)
b = np.arange(5., 21, 0.2)
c = np.arange(1, 10)
d = np.arange(5)
print(a)
print(b)
print(c)
print(d)

[ 1  5  9 13]
[ 5.   5.2  5.4  5.6  5.8  6.   6.2  6.4  6.6  6.8  7.   7.2  7.4  7.6
  7.8  8.   8.2  8.4  8.6  8.8  9.   9.2  9.4  9.6  9.8 10.  10.2 10.4
 10.6 10.8 11.  11.2 11.4 11.6 11.8 12.  12.2 12.4 12.6 12.8 13.  13.2
 13.4 13.6 13.8 14.  14.2 14.4 14.6 14.8 15.  15.2 15.4 15.6 15.8 16.
 16.2 16.4 16.6 16.8 17.  17.2 17.4 17.6 17.8 18.  18.2 18.4 18.6 18.8
 19.  19.2 19.4 19.6 19.8 20.  20.2 20.4 20.6 20.8]
[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


***Последовательности чисел с постоянным шагом можно также создавать функцией `linspace`. Начало и конец диапазона включаются; последний аргумент -- число точек.***

In [24]:
a = np.linspace(1, 15, 20)
b = np.linspace(5, 12, 10)
print(a)
print(b)

[ 1.          1.73684211  2.47368421  3.21052632  3.94736842  4.68421053
  5.42105263  6.15789474  6.89473684  7.63157895  8.36842105  9.10526316
  9.84210526 10.57894737 11.31578947 12.05263158 12.78947368 13.52631579
 14.26315789 15.        ]
[ 5.          5.77777778  6.55555556  7.33333333  8.11111111  8.88888889
  9.66666667 10.44444444 11.22222222 12.        ]


**Задача 2:** создать и вывести последовательность чисел от 10 до 32 с постоянным шагом, длина последовательности -- 12. Чему равен шаг?

In [25]:
# решение

a = np.linspace(10, 32, 12)
print(a)
print(a[1] - a[0])



[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32.]
2.0


***Последовательность чисел с постоянным шагом по логарифмической шкале от $10^0$ до $10^3$.***

In [26]:
b = np.logspace(0, 3, 12)
print(b)

[   1.            1.87381742    3.51119173    6.57933225   12.32846739
   23.101297     43.28761281   81.11308308  151.9911083   284.80358684
  533.66992312 1000.        ]


### Операции над одномерными массивами.

***Все арифметические операции производятся поэлементно.***

In [27]:
print(a)
print(b)

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32.]
[   1.            1.87381742    3.51119173    6.57933225   12.32846739
   23.101297     43.28761281   81.11308308  151.9911083   284.80358684
  533.66992312 1000.        ]


In [28]:
a = np.linspace(3, 33, 11)
b = np.linspace(-2, -22, 11)
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55.]
[  -6.  -24.  -54.  -96. -150. -216. -294. -384. -486. -600. -726.]
[-1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5]


***Один из операндов может быть скаляром, а не массивом.***

In [29]:
print(5*a)
print(10 + b)

[ 15.  30.  45.  60.  75.  90. 105. 120. 135. 150. 165.]
[  8.   6.   4.   2.   0.  -2.  -4.  -6.  -8. -10. -12.]


In [30]:
print((a + b) ** 2)
print(2 ** (a + b))

[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121.]
[2.000e+00 4.000e+00 8.000e+00 1.600e+01 3.200e+01 6.400e+01 1.280e+02
 2.560e+02 5.120e+02 1.024e+03 2.048e+03]


***Если типы элементов разные, то идет каст к большему.***

In [31]:
print(a + np.arange(11, dtype='int16'))
print(type(a[0]))

[ 3.  7. 11. 15. 19. 23. 27. 31. 35. 39. 43.]
<class 'numpy.float64'>


***В ``Numpy`` есть элементарные функции, которые тоже применяются к массивам поэлементно. Они называются универсальными функциями (``ufunc``).***

In [32]:
type(np.cos)

numpy.ufunc

In [33]:
np.cos(a)

array([-0.9899925 ,  0.96017029, -0.91113026,  0.84385396, -0.75968791,
        0.66031671, -0.54772926,  0.42417901, -0.29213881,  0.15425145,
       -0.01327675])

In [34]:
np.log(b)

/tmp/ipykernel_2722/4200754868.py:1: RuntimeWarning: invalid value encountered in log
  np.log(b)


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

***Логические операции также производятся поэлементно.***

In [35]:
print(a > b)
print(a == b)
print(a >= 10)

[ True  True  True  True  True  True  True  True  True  True  True]
[False False False False False False False False False False False]
[False False False  True  True  True  True  True  True  True  True]


***Кванторы ``всеобщности`` и ``существования``.***
$$\forall$$
$$\exists$$

In [36]:
c = np.arange(0., 20)
print(type(c[0]))

<class 'numpy.float64'>


In [37]:
np.any(c == 0.), np.all(c)

(True, False)

***Inplace операции.***

In [38]:
c += np.sin(4)
print(c)

[-0.7568025  0.2431975  1.2431975  2.2431975  3.2431975  4.2431975
  5.2431975  6.2431975  7.2431975  8.2431975  9.2431975 10.2431975
 11.2431975 12.2431975 13.2431975 14.2431975 15.2431975 16.2431975
 17.2431975 18.2431975]


***Inplace операции возможны только для операндов одинакового типа.***

In [39]:
c *= 2
print(c)

[-1.51360499  0.48639501  2.48639501  4.48639501  6.48639501  8.48639501
 10.48639501 12.48639501 14.48639501 16.48639501 18.48639501 20.48639501
 22.48639501 24.48639501 26.48639501 28.48639501 30.48639501 32.48639501
 34.48639501 36.48639501]


In [40]:
b = np.arange(1., 21, 1)

d = (b + c)
d /= b
print(d)

[-0.51360499  1.2431975   1.82879834  2.12159875  2.297279    2.41439917
  2.49805643  2.56079938  2.60959945  2.6486395   2.68058136  2.70719958
  2.72972269  2.74902821  2.76575967  2.78039969  2.79331735  2.80479972
  2.81507342  2.82431975]


***При делении ``ndarray`` на нули, исключения не бросается.***

In [41]:
print(np.array([0.0, 0.0, 1.0, -1.0]) / np.array([1.0, 0.0, 0.0, 0.0]))

[  0.  nan  inf -inf]


/tmp/ipykernel_2722/3088186758.py:1: RuntimeWarning: divide by zero encountered in divide
  print(np.array([0.0, 0.0, 1.0, -1.0]) / np.array([1.0, 0.0, 0.0, 0.0]))
/tmp/ipykernel_2722/3088186758.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array([0.0, 0.0, 1.0, -1.0]) / np.array([1.0, 0.0, 0.0, 0.0]))


***Могут понадобится константы.***

In [42]:
print(np.e, np.pi)

2.718281828459045 3.141592653589793


In [43]:
print(b)
print(b.cumsum())

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
[  1.   3.   6.  10.  15.  21.  28.  36.  45.  55.  66.  78.  91. 105.
 120. 136. 153. 171. 190. 210.]


***Посмотрим на сортировку numpy-массивов.***

In [44]:
a = np.array([1, 5, 6, 10, -2, 0, 18])

In [45]:
print(np.sort(a))
print(a)

[-2  0  1  5  6 10 18]
[ 1  5  6 10 -2  0 18]


***Теперь попробуем как метод.***

In [46]:
a.sort()
print(a)

[-2  0  1  5  6 10 18]


In [47]:
b = np.ones(5)
b

array([1., 1., 1., 1., 1.])

***Объединим массивы.***

In [48]:
c = np.hstack((a, b, 5*b))
c

array([-2.,  0.,  1.,  5.,  6., 10., 18.,  1.,  1.,  1.,  1.,  1.,  5.,
        5.,  5.,  5.,  5.])

In [49]:
?np.hsplit


Signature: np.hsplit(ary, indices_or_sections)
Docstring:
Split an array into multiple sub-arrays horizontally (column-wise).

Please refer to the `split` documentation.  `hsplit` is equivalent
to `split` with ``axis=1``, the array is always split along the second
axis except for 1-D arrays, where it is split at ``axis=0``.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.hsplit(x, 2)
[array([[  0.,   1.],
       [  4.,   5.],
       [  8.,   9.],
       [12.,  13.]]),
 array([[  2.,   3.],
       [  6.,   7.],
       [10.,  11.],
       [14.,  15.]])]
>>> np.hsplit(x, np.array([3, 6]))
[array([[ 0.,   1.,   2.],
       [ 4.,   5.,   6.],
       [ 8.,   9.,  10.],
       [12.,  13.,  14.]]),
 array([[ 3.],
       [ 7.],
       [11.],
       [15.]]),
 array([

***Расщепление массива.***

In [50]:
x1, x2, x3, x4 = np.hsplit(a, [3, 5, 6])
print(a)
print(x1)
print(x2)
print(x3)
print(x4)

[-2  0  1  5  6 10 18]
[-2  0  1]
[5 6]
[10]
[18]


***Функции ``append`` ``delete`` ``insert`` не Inplace функции.***

In [51]:
print(np.delete(a, [2, 4, 1]))
print(a)

[-2  5 10 18]
[-2  0  1  5  6 10 18]


In [52]:
np.insert(a, 2, [-1, -1])

array([-2,  0, -1, -1,  1,  5,  6, 10, 18])

In [53]:
np.append(a, [2.2, 2.1])

array([-2. ,  0. ,  1. ,  5. ,  6. , 10. , 18. ,  2.2,  2.1])

## Cрезы

***Массив в обратном порядоке.***

In [54]:
a[::-1]

array([18, 10,  6,  5,  1,  0, -2])

***Диапазон индексов. Создаётся новый заголовок массива, указывающий на те же данные. Изменения, сделанные через такой массив, видны и в исходном массиве.***

In [55]:
print(a)

[-2  0  1  5  6 10 18]


In [56]:
a[2:5]

array([1, 5, 6])

In [57]:
b = a[0:6] # копия не создается
b[1] = -1000
print(a)

[   -2 -1000     1     5     6    10    18]


***Диапозоны с шагами.***

In [58]:
b = a[0:4:2]
print(b)

# подмассиву можно присваивать скаляр
a[1:6:3] = 0
print(a)

[-2  1]
[-2  0  1  5  0 10 18]


***Чтобы скопировать и данные массива, нужно использовать метод ``copy``.***

In [59]:
b = a.copy()
b[2] = -4
print(b)
print(a)

[-2  0 -4  5  0 10 18]
[-2  0  1  5  0 10 18]


In [60]:
print(a[[5,3,1]]) # массив индексов

[10  5  0]


**Задание 3:**  
- Создать массив чисел от $-4\pi$  до $4\pi $, количество точек 100
- Посчитать сумму поэлементных квадратов синуса и косинуса для данного массива  
- С помощью ``np.all`` проверить, что все элементы равны единице.

In [61]:
# решение

x = np.linspace(-4*np.pi, 4*np.pi, 100)
print(np.sin(x)**2 + np.cos(x)**2)
np.all((np.sin(x)**2 + np.cos(x)**2).round() == 1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


True

## Матрицы

**Определение**: *Матрицей размера $m \times n$* нахывается прямоугольная таблица с числами из $m$ строк и $n$ столбцов: 

$$\begin{pmatrix}x_{11}, x_{12}, ... , x_{1n}\\x_{21}, x_{22}, ... , x_{2n}\\...\ \ \ ...\ \ \ ...\\x_{m1}, x_{m2}, ... , x_{mn}\\\end{pmatrix}$$

**Определение**: Квадратная матрица называется *(не)вырожденой*, если ее строки линейно (не)зависимы
$$\begin{pmatrix}1\ \ \ \ \ \ 3\ \ \ \ \ \ -1\\0\ \ \ \ \ \ -2\ \ \ \ \ \ 0\\2\ \ \ \ \ \ 4\ \ \ \ \ \ -2 \end{pmatrix}$$

**Утверждение**: Строки квадратной матрицы ЛНЗ тогда и только тогда, когда её столбцы ЛНЗ

**Определение**: *Строчным рангом* матрицы $A$ называется размер наибольшего подмножества линейно независимых строк $A$. Аналогчно определяется *столбцовый* ранг.

**Пример**: 
$$\begin{pmatrix}1\ \ \ \ \ \ 0\ \ \ \ \ \ 0\ \ \ \ \ \ 5\ \ \ \ \ \ -2\\0\ \ \ \ \ \ 1\ \ \ \ \ \ 0\ \ \ \ \ \ 0\ \ \ \ \ \ -1\\0\ \ \ \ \ \ \ 0\ \ \ \ \ \ \ 1\ \ \ \ \ \ \ 2\ \ \ \ \ \ \ 3\\ \end{pmatrix} \\ Строчный\ и\ столбцовый\ ранг\ равны\ 3$$

**Удтверждение**: Строчный и столбцовый ранг равны.

#### Умножение матрицы на вектор

![](imgs/sem1/sem1_9.png)

Пример с системой линейных уравнений, ее можно очень удобно записать в матричном виде:

![](imgs/sem1/sem1_10.png)


##### Линейная регрессия в матричном виде
- Ищем закономерность в *линейном* виде $$y_k = w_1x_{k1} + w_2x_{k2} + ... + w_nx_{kn}$$
- В матричном виде уравнение записывается так: 
$$Xw = y$$
$$X = \begin{pmatrix}x_{11}, x_{12}, ... , x_{1n}\\x_{21}, x_{22}, ... , x_{2n}\\...\ \ \ ...\ \ \ ...\\x_{m1}, x_{m2}, ... , x_{mn}\\\end{pmatrix}, w = \begin{pmatrix}w_1\\w_2\\ ... \\ w_{n} \end{pmatrix}, y = \begin{pmatrix}w_1\\y_2\\ ... \\ y_{n} \end{pmatrix}$$

Любой алгоритм машинного обучения очень чувствителен к количеству объектов ($m$) и количеству признаков ($n$) в обучающей выборке:

- Если $m = n$, то решение (скорее всего) единственное.
- Если $m > n$, то решение (скорее всего) нет.
- Если $m < n$, то решение (скорее всего) бесконечно много.

### Матрицы в NumPy

In [62]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [63]:
a.ndim, a.shape, len(a), a.size

(2, (2, 2), 2, 4)

***Обращение по индексу.***

In [64]:
a[1][1], a[1,1]

(4, 4)

***Атрибуту ``shape`` можно присвоить новое значение -- кортеж размеров по всем координатам. Получится новый заголовок массива; его данные не изменятся.***

In [65]:
b = np.arange(0, 20)
b.shape = (2, 10)
print(b)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [66]:
print(b.reshape((1,20))) # то же самое, что и shape

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]


In [67]:
print(b.ravel()) # стягивание в одномерный массив

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [68]:
a = np.ones((3, 3)) # подать tuple
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [69]:
b = np.zeros((3, 4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### Операции над матрицами

- Сложение матриц
- Умножение матриц
- Транспонирование и обратная матрица
- Определитель матрицы

##### Сложение матриц
- выполняется поэлементно
- Можно применять только к матрицам одинакового размера

![](imgs/sem1/sem1_11.png)

In [70]:
a = np.ones((3, 3)) # подать tuple
b = np.ones((3, 3)) # подать tuple


a + b

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

##### Умножение матриц

- Можно применять только к матрицам, в которых количество столбцов одной матрицы совпадает с количеством строк второй.

![](imgs/sem1/sem1_12.png)

Произведение матриц встречается, когда совокупность векторов умножается на матрицу (например при подаче в нейронную сеть батча данных)

##### Свойства произведения матриц
- Ассоциативность: $A(BC) = (AB)C$
- Дистрибутивность: $A(B + C) = AB + АC$
- Отсутствие коммутативности: не всегда $AB = BA$
- Существование нейтрального элемента $E$ (Единичная матрица): $$\begin{pmatrix}1\ 0\ ...\ 0\\0\ 1\ ...\ 0\\.........\\0\ 0\ ...\ 1\\\end{pmatrix}$$ $$AE = EA = A$$
- Для квадратных матриц: если $A$ вырождена, то $AB$ также вырождена

In [71]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [72]:
a = 5*np.ones((5, 5))
b = np.eye(5) + 1
print(a, '\n')
print(b)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]] 

[[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]


In [73]:
print(a * b, '\n') # поэлементное умножение
print(a @ b, '\n') # матричное умножение
print(a.dot(b)) 

[[10.  5.  5.  5.  5.]
 [ 5. 10.  5.  5.  5.]
 [ 5.  5. 10.  5.  5.]
 [ 5.  5.  5. 10.  5.]
 [ 5.  5.  5.  5. 10.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]]


In [74]:
c = np.eye(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [75]:
d = np.diag([1, 2, 3, 'a'])
print(d)

[['1' '' '' '']
 ['' '2' '' '']
 ['' '' '3' '']
 ['' '' '' 'a']]


***Задание 4:***
Создать квадратную матрицу размера 8, на главной диаг. арифметическая прогрессия с шагом 3 (начиная с 3), а на побочной -1, остальные элементы 0.

In [76]:
# решение
# print(-1*np.eye(8)[::-1][::-1])
a = -1*np.eye(8)[::-1] + np.diag(np.arange(3, 27, 3))
print(a)


[[ 3.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  6.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  9.  0.  0. -1.  0.  0.]
 [ 0.  0.  0. 12. -1.  0.  0.  0.]
 [ 0.  0.  0. -1. 15.  0.  0.  0.]
 [ 0.  0. -1.  0.  0. 18.  0.  0.]
 [ 0. -1.  0.  0.  0.  0. 21.  0.]
 [-1.  0.  0.  0.  0.  0.  0. 24.]]


##### Обратная матрица
**Определение**: Пусть  $A$ - квадратная матрица. Если существует такая матрица $A^{-1}$, что $AA^{-1} = A^{-1}A = E$, то матрица $A^{-1}$ называется *обратной матрицей* к $A$. Матрица $A$ в таком случае называется *обратимой*.

**Утверждение**: Пусть $A$ - квадратная матрица. Если строки (или столбцы) $А$ линейно независимы (т.е. $A$ невырождена), то обратная матрица существует и единствена.

##### Обратная матрица при решении СЛУ

Есть СЛУ: $$Ax = b$$

Если существует $A^{-1}$, то у системы есть единственное решение: $$x = A^{-1}b$$

##### Транспонированная матрица

Транспонирование - операция отражения матрицы относительно главной диагонали. Обозначается как $A^{\top}$

Вектор-столбец при транспонировании переходит в вектор-строку. Поэтому скалярное произведение можно записать так: $$<x, y> = x^{\top}y$$

In [77]:
a = np.array([[0, 1, 2], [4, 5, 6]])
b = a.transpose()
print(a)
print()
print(b)

[[0 1 2]
 [4 5 6]]

[[0 4]
 [1 5]
 [2 6]]


##### Определитель матрицы

Определитель квадратной матрицы - это ее числовая характеристика.

- $\mid a\mid = a$
- $\mid\begin{pmatrix}a\ b\\c\ d \end{pmatrix}\mid = ad - bc$

![](imgs/sem1/sem1_13.png)

##### Свойства определителя
- $\mid AB \mid = \mid A \mid \mid B \mid$ 
- $\mid A \mid = 0$ тогда и только тогда, когда $A$ вырожденная

##### Вычисление обратной матрицы с помощью определителей

![](imgs/sem1/sem1_14.png)

In [78]:
a = np.array([[2, 1], [2, 3]])
print(a)

[[2 1]
 [2 3]]


In [79]:
np.linalg.det(a)

4.0

***Нахождениия обратной.***

In [80]:
b = np.linalg.inv(a)
print(b)

[[ 0.75 -0.25]
 [-0.5   0.5 ]]


In [81]:
print(a.dot(b))
print(b.dot(a))

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [82]:
c = np.array([[2, 1], [6, 3]])
print(c)
print(np.linalg.det(c))

[[2 1]
 [6 3]]
0.0


In [83]:
np.linalg.inv(c)

LinAlgError: Singular matrix

***Решение НЛУ.***
$$ A \cdot x = v $$

In [84]:
v = np.array([5, -10])
print(np.linalg.solve(a, v))
print(b.dot(v))

[ 6.25 -7.5 ]
[ 6.25 -7.5 ]


***Найдем собственные вектора матрицы A.***
$$ A \cdot x = \lambda \cdot x $$

In [85]:
l, u = np.linalg.eig(a)
print(l)
print(u)

[1. 4.]
[[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]


***Собственные значения матриц A и A.T совпадают.***

In [86]:
l, u = np.linalg.eig(a.T)
print(l)
print(u)

[1. 4.]
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [87]:
l, u = np.linalg.eig(np.eye(3))
print(l)
print(u)

[1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Еще чутка numpy

***Маски.***

In [88]:
a = np.arange(20)
print(a)
print(a % 3 == 0)
print(a[a % 3 == 0])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ True False False  True False False  True False False  True False False
  True False False  True False False  True False]
[ 0  3  6  9 12 15 18]


In [89]:
b = np.diag(a[a >= 10])
print(b)
print(np.trace(b))

[[10  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0]
 [ 0  0  0 13  0  0  0  0  0  0]
 [ 0  0  0  0 14  0  0  0  0  0]
 [ 0  0  0  0  0 15  0  0  0  0]
 [ 0  0  0  0  0  0 16  0  0  0]
 [ 0  0  0  0  0  0  0 17  0  0]
 [ 0  0  0  0  0  0  0  0 18  0]
 [ 0  0  0  0  0  0  0  0  0 19]]
145


## Шлифанем тестами на производительность

***Производительность.***

Без Numpy:

In [90]:
%%time
def summ(a):
    ans = 0
    for i in a:
        ans += i
    return ans

arr = range(10**7)

print(summ(arr))

49999995000000
CPU times: user 469 ms, sys: 0 ns, total: 469 ms
Wall time: 503 ms


C Numpy:

In [91]:
%%time

sum_value = np.sum(np.arange(10**7))
print(sum_value)

49999995000000
CPU times: user 15.6 ms, sys: 109 ms, total: 125 ms
Wall time: 108 ms


Без Numpy:

In [92]:
%%time
arr = []
n = 10**7
for i in range(n):
    arr.append(i*5)

CPU times: user 1.12 s, sys: 578 ms, total: 1.7 s
Wall time: 1.69 s


С Numpy:

In [93]:
%%time
arr = 5*np.arange(10**7)

CPU times: user 93.8 ms, sys: 109 ms, total: 203 ms
Wall time: 216 ms


# Лабораторная 1

Решить 100 numpy задач, дедлайн `01.04.2023`

https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb