# Домашнее задание #1

Для начала вам понадобится импортировать модуль `numpy` как `np`

In [1]:
import numpy as np

## Задача №1

Считайте (через `input`) 2 числа: <br>
`n` - размер `Numpy` вектора; <br>
`x` - координата элемента вектора, который должен быть равен `1`. Остальные должны быть равны `0`. <br>
Создайте вектор размера `n`, в котором все элементы равны `0`, кроме элемента с номером `x` - он равен `1`.


In [2]:
print("Введите размер матрицы через пробел")
n, x = map(int, input().split())

Введите размер матрицы через пробел
5 1


In [3]:
vec = np.zeros(n)
vec[x] = 1

vec

array([0., 1., 0., 0., 0.])

## Задача №2

Считайте 3 числа: `n, m, s`. Создайте `Numpy` вектор, состоящий из чисел от `n` до `m` с шагом `s`.

In [6]:
print("Введите три числа через пробел")
n, m, s = map(int, input().split())

Введите три числа через пробел
1 10 2


In [7]:
vec = np.arange(n, m, s)

vec

array([1, 3, 5, 7, 9])

## Задача №3

Создайте матрицу `3х3` со значениями от `0` до `8`. Значения нужно сгенерировать.

In [8]:
np.random.randint(low=0, high=8, size=(3,3))

array([[2, 5, 1],
       [7, 2, 6],
       [2, 5, 6]])

## Задача №4

1. Создайте матрицу `4х4` со случайными значениями.
2. Найдите максимальное значение первой строки, минимальное - второй, среднее - третьей, сумму - четвертой.

In [9]:
np.random.seed(seed=5)
array = np.random.rand(4, 4)

In [10]:
print(f'max {np.max(array[0, :]).round(4)}')
print(f'min {np.min(array[1, :]).round(4)}')
print(f'mean {np.mean(array[2, :]).round(4)}')
print(f'sum {np.sum(array[3, :]).round(4)}')

max 0.9186
min 0.4884
mean 0.3259
sum 1.7536


## Задача №5

Создайте диагональную матрицу `5х5`, все ненулевые элементы равны 5.

In [11]:
np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Задача №6

Создайте `Numpy` массив случайных чисел размерности `6х6х6` и найдите максимальное значение среди всех элементов.

In [12]:
matrix = np.random.rand(6,6,6)
print("Максимальное число: " + str(np.max(matrix).round(4)))

Максимальное число: 0.9972


## Задача №7

Напишите функцию, которая принимает на вход 2 `Numpy` матрицы, проверяет, можно ли их перемножить, и если можно - то перемножает и возвращает транспонированную результирующую матрицу.

In [13]:
def cond_and_mult_and_trans(A, B):
    if A.shape[1] == B.shape[0]:
        return np.transpose(A @ B)
    
    return "Невозможно перемножать"


In [14]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 2, 3], [3, 4, 5], [2, 2, 3]])

cond_and_mult_and_trans(A, B)

'Невозможно перемножать'

In [15]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 2], [3, 4]])

cond_and_mult_and_trans(A, B)

array([[ 7, 15],
       [10, 22]])

## Задача №8

Эту задачу можете как запрограммировать, так и решить на листочке.

Но проще, конечно, **запрограммировать**.

Здесь вам придется заглянуть в ноутбук ["Функция одной переменной/Производная функции многих переменных"](./Derivative.ipynb) и убедиться, что вы поняли, как дифференцировать функцию многих переменных, а также в ноутбук ["Оптимизация функции одной и многих переменных"](./Optimization.ipynb) и убедиться, что вы поняли, как работает градиентный спуск. Если все-таки не поняли - пишите в [чат](https://t.me/joinchat/01_ttlSQj3hjZTg6), тегайте меня, `@leonidt`, пришлю вам что-нибудь в помощь.

Дана функция:

$$ f(x_1, x_2) = x_1^2 + 2x_2^2 + e^{x_1+x_2} $$

Найдите минимум данной функции, завершив вычисления при погрешности $$\varepsilon = 0.5 $$, выбрав в качестве начального приблежения точку `(0, 0)` и коэффициент шага $$ H=0.1. $$

In [16]:
def func(x, y):
    return x*x + 2.0 * y*y + np.exp(x + y)

def f_x(func, x, y, eps=0.001):
    return (func(x+eps, y) - func(x, y)) / eps

def f_y(func, x, y, eps=0.001):
    return (func(x, y+eps) - func(x, y)) / eps

In [17]:
EPS = 0.001
INIT = np.array([1.0, -1.75])
LEARN_RATE = 0.05
ITER = 10000

X_prev = INIT
delta = 1
for i in range(ITER):
    if delta > EPS:
        fxx = f_x(func, X_prev[0], X_prev[1], eps=0.001)
        fyy = f_y(func, X_prev[0], X_prev[1], eps=0.001)
        grad = np.array([fxx, fyy])

        X_next = X_prev - LEARN_RATE * grad    

        delta = np.sqrt(np.sum(grad*grad))
        
        X_prev = X_next
        
    else:
        break

In [18]:
print(f"Значение функции {func(X_next[0], X_next[1]).round(4)}")
print(f"x_min {X_next[0].round(4)}")
print(f"y_min {X_next[1].round(4)}")
print(f"Производная в x_min {f_x(func, X_next[0], X_next[1], eps=0.001).round(4)}")
print(f"Производная в y_min {f_y(func, X_next[0], X_next[1], eps=0.001).round(4)}")
print(f"Градиент {np.sqrt((grad**2).sum()).round(9)}")


Значение функции 0.7723
x_min -0.3128
y_min -0.1569
Производная в x_min 0.0008
Производная в y_min -0.0002
Градиент 0.000963264
